# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-11 13:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.TextField()),
                ('client_phone', models.CharField(max_length=10)),
                ('client_address', models.TextField()),
            ],
        ),
    ]
