# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-11 14:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('getdata', '0002_auto_20170311_1418'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GetData',
            new_name='GetClient',
        ),
    ]
