# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-13 20:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getdata', '0003_auto_20170311_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='getclient',
            name='client_address',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='getclient',
            name='client_name',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='getclient',
            name='client_phone',
            field=models.CharField(default=None, max_length=10),
        ),
    ]
