# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-21 00:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getdata', '0004_auto_20170313_2002'),
    ]

    operations = [
        migrations.AddField(
            model_name='getclient',
            name='balance',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='getclient',
            name='comments',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='getclient',
            name='dob',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='getclient',
            name='driver_no',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='getclient',
            name='log_no',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='getclient',
            name='no_of_lessons',
            field=models.TextField(default=None),
        ),
    ]
