# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-21 00:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getdata', '0005_auto_20170321_0023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='getclient',
            name='balance',
            field=models.CharField(default=None, max_length=10),
        ),
        migrations.AlterField(
            model_name='getclient',
            name='dob',
            field=models.DateField(default=None),
        ),
        migrations.AlterField(
            model_name='getclient',
            name='driver_no',
            field=models.CharField(default=None, max_length=10),
        ),
        migrations.AlterField(
            model_name='getclient',
            name='log_no',
            field=models.CharField(default=None, max_length=10),
        ),
        migrations.AlterField(
            model_name='getclient',
            name='no_of_lessons',
            field=models.CharField(default=None, max_length=10),
        ),
    ]
