# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-21 01:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getdata', '0007_remove_getclient_client_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='getclient',
            name='client_address',
            field=models.TextField(default=None),
        ),
    ]
