# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-21 01:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('getdata', '0008_getclient_client_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='getclient',
            name='balance',
        ),
        migrations.RemoveField(
            model_name='getclient',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='getclient',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='getclient',
            name='driver_no',
        ),
        migrations.RemoveField(
            model_name='getclient',
            name='log_no',
        ),
        migrations.RemoveField(
            model_name='getclient',
            name='no_of_lessons',
        ),
    ]
